version: '3.7'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  db_data:
    name: ${VOLUME_DB_ID}

services:
  nginx:
    image: hexbatch/nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      backend:
        aliases:
          - ${APP_HOST}

  php-fpm:
    image: hexbatch/php-fpm
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TARGET_PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    environment:
      - GK_MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - GK_MYSQL_USER=${DB_MYSQL_USER}
      - GK_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - GK_MYSQL_PORT=${DB_MYSQL_OWNPORT}
      - GK_MYSQL_CHARSET=${DB_MYSQL_CHARSET}
      - GK_MYSQL_HOST=db
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    networks:
      - backend

  workspace:
    image: hexbatch/workspace
    build:
      context: .
      dockerfile: ./workspace/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TARGET_PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    environment:
      - GK_MYSQL_DATABASE=${DB_MYSQL_DATABASE}
      - GK_MYSQL_USER=${DB_MYSQL_USER}
      - GK_MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - GK_MYSQL_PORT=${DB_MYSQL_OWNPORT}
      - GK_MYSQL_CHARSET=${DB_MYSQL_CHARSET}
      - GK_MYSQL_HOST=db
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "${WORKSPACE_HOST_SSH_PORT}:22"
    networks:
      - backend
